### ISSUE TITLE
Crash when fetch returns a null item

### ISSUE THREAD

**Issue by mokesmokes** [viezel/napp.alloy.adapter.restapi#58]
My responseJSON is `[null]` (which is a valid JSON response), and then the adapter starts looping on the items, trying to set `item[model.idAttribute]`, e.g. https://github.com/viezel/napp.alloy.adapter.restapi/blob/master/restapi.js#L274
All such cases should be changed to something like:
`if (item && item[model.idAttribute] === undefined)`
Also note that https://github.com/viezel/napp.alloy.adapter.restapi/blob/master/restapi.js#L273 overwrites the empty object from the previous line, this is not the intent.

**Comment by brandonneil** [comment]
I've also run into this problem and have supplied a pull request making the above change.
